import type { Metadata } from 'next'
import StoreProvider from './StoreProvider'
import './styles/_reset.scss'
import { Body } from './Body'

export const metadata: Metadata = {
  title: 'kateVR',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <Body>{children}</Body>
      </html>
    </StoreProvider>
  )
}
