import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './styles/_reset.scss'
import StoreProvider from './StoreProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'kateVR',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`${inter.className} page`}>{children}</body>
      </html>
    </StoreProvider>
  )
}
